---

- name: install prerequisites for ruuvi-collector
  apt:
    name: "{{ item }}"
  with_items:
    - openjdk-17-jre-headless
    - bluez
    - bluez-hcidump
  notify: add bluetooth capabilities for hcitool and hcidump

- name: create directory for ruuvi-collector
  file:
    path: /etc/ruuvi-collector
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: download ruuvi-collector
  get_url:
    url: "https://github.com/Scrin/RuuviCollector/releases/download/{{ ruuvicollector_version }}/{{ ruuvicollector_release_filename }}"
    dest: "/etc/ruuvi-collector/ruuvi-collector.jar"
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate ruuvi-collector config
  template:
    src: ruuvi-collector.properties.j2
    dest: /etc/ruuvi-collector/ruuvi-collector.properties
    owner: root
    group: root
    mode: '0644'
  notify: restart ruuvi-collector

- name: generate ruuvi-names config
  template:
    src: ruuvi-names.properties.j2
    dest: /etc/ruuvi-collector/ruuvi-names.properties
    owner: root
    group: root
    mode: '0644'
  notify: restart ruuvi-collector

- name: service information for ruuvi-collector
  copy:
    src: ruuvi-collector.service
    dest: /etc/systemd/system/ruuvi-collector.service
    owner: root
    group: root
    mode: '0644'
  notify: restart ruuvi-collector

- name: flush handlers
  meta: flush_handlers

- name: start ruuvi-collector
  service:
    name: ruuvi-collector
    enabled: true
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
