---

- name: add bluetooth capabilities for hcitool and hcidump
  capabilities:
    path: "{{ item }}"
    capability: "cap_net_raw,cap_net_admin+eip"
    state: present
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  with_items:
    - "/usr/bin/hcitool"
    - "/usr/bin/hcidump"

- name: restart ruuvi-collector
  systemd:
    name: ruuvi-collector
    state: restarted
    daemon_reload: yes
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

